#!/bin/bash

. CREDENTIALS
. nohosts

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo 'usage: connect [instance_number] '
	echo
	echo "NB: instance_numbers count from 0"
	exit 2
fi

instance_number=$1
[ -z $instance_number ] && instance_number=0
[ ! -f './.reservation' ] && { echo 'No .reservation file found'; exit 1; }
reservation_id=`cat ./.reservation`
instances=`ec2-describe-instances --filter reservation-id=$reservation_id | grep ^INSTANCE`
hostnames=`echo "${instances}" | cut -f4`
hostnames_arr=($hostnames)
len=${#hostnames_arr[@]}
[ $instance_number -ge $len ] && { echo Error: host index out of bounds \($len hosts running, indexes start from 0\); exit 1; }
hostname=${hostnames_arr[instance_number]}
sshnh ${login_user}@${hostname}

