#!/bin/bash

function getreservation () {
	if [ $1 ]; then
		if [ -f $1 ]; then
			reservation_id=`cat "$1"`
		else
			echo "Could not find reservation file $1"
			exit 1
		fi
	else
		if [ -f './.reservation' ]; then
			reservation_id=`cat ./.reservation`
		else
			echo 'No .reservation file found'
			exit 1
		fi
	fi
}

