#!/bin/bash

# import credentials and functions
. CREDENTIALS
. nohosts

if [ $# -eq 0 ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo "usage: $0 pkg_file.tar.bz2"
	exit 2
fi

package_file=$1
[ ! -f './.reservation' ] && { echo 'No .reservation file found'; exit 1; }
reservation_id=`cat ./.reservation`
[ ! $package_file ] || [ ! -f $package_file ] && { echo "Package file not found: $package_file"; exit 1; }

# wait until all instances are in "running" status
while true; do
	instances=`ec2-describe-instances --filter reservation-id=$reservation_id | grep ^INSTANCE`
	statuses=`echo "${instances}" | cut -f6`
	finished=1
	for status in $statuses; do
		[ "$status" != "running" ] && finished=0
	done
	[ $finished -eq 1 ] && break
done

# inject into each host the seeds file & package contents, and launch
hostnames=`echo "${instances}" | cut -f4`
for hostname in $hostnames; do
	
	# make list of other hosts (all hosts excluding the current one)
	other_hosts=`echo $hostnames | tr ' ' '\n' | grep -v $hostname`
	
	# The command below both sends the $package_file and a script in one ssh connection
	#
	# Command does the following:
	# 	1) dumps list of other hosts into a newline-delimited file at /var/vcloud/other_hosts
	#	2) creates and enters 'vcloud-deploy' subdir of $login_user's $HOME
	#	3) dumps $package_file as '.vcloud-data' and also decompresses it into ./
	#	4) looks for vcloud-launch in 2 places (in this order):
	#		1) current directory (i.e. the 'root' of the $package_file)
	#		2) a single sub-dir contained in the $package_file
	#	5) executes the first script found and exits
	#
	#	NB: if vcloud-launch script not found in root and number of subdirs != 1
	#	then fail
	
	cat $package_file | sshnh $login_user@$hostname "
		sudo -n bash -c \"mkdir -p /var/vcloud; echo '${other_hosts}' | tr ' ' '\n' > /var/vcloud/other_hosts\";
		rm -rf vcloud-deploy; mkdir vcloud-deploy; cd vcloud-deploy;
		tee .vcloud-data | tar jx;
		[ -f ./vcloud-launch ] && { screen -d -m ./vcloud-launch; exit; };
		dirs=(\$(ls -1F | grep '\/$'));
		[ \${#dirs[@]} -eq 1 ] && { cd \${dirs[0]}; screen -d -m ./vcloud-launch; exit; }" &

done
wait

