#!/bin/bash

# import credentials and functions
. CREDENTIALS
. nohosts

if [ $# -eq 0 ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo "usage: $0 pkg_file.tar.bz2"
	exit 2
fi

package_file=$1
[ ! $package_file ] || [ ! -f $package_file ] && { echo "Package file not found: $package_file" >&2; exit 1; }
[ ! -f ${HOME}/.vcloud-reservations ] && { echo 'No reservations found' >&2; exit 1; }
reservation_filters=$(cat ${HOME}/.vcloud-reservations | sed 's/^/--filter reservation-id=/')

# wait for machines in all reservations to enter 'running' status
while true; do
	instances=`ec2-describe-instances $reservation_filters | grep ^INSTANCE`
	statuses=`echo "${instances}" | cut -f6`
	finished=1
	for status in $statuses; do
		[ "$status" != "running" ] && finished=0
	done
	[ $finished -eq 1 ] && break
done
wait

# inject into each host the seeds file & package contents, and launch
hostnames=`echo "${instances}" | cut -f4`
for hostname in $hostnames; do
	
	# make list of other hosts (all hosts excluding the current one)
	other_hosts=`echo $hostnames | tr ' ' '\n' | grep -v $hostname`
	
	# The command below both sends and sets up $package_file in one ssh connection
	#
	# Command does the following on the remote machine:
	# 	1) dumps list of other hosts into a newline-delimited file at /var/vcloud/other_hosts
	#	2) dumps $package_file as '.vcloud-data' and also decompresses it
	#	3) looks for vcloud-launch in 2 places (in this order):
	#		1) current directory (i.e. the 'root' of the uncompressed $package_file)
	#		2) a single sub-dir contained at the root of the uncompressed $package_file
	#	4) executes the first script found and exits
	#
	#	NB: if vcloud-launch script not found in root and number of subdirs != 1
	#	then fail
	
	cat $package_file | sshnh $login_user@$hostname "
		sudo -n bash -c \"mkdir -p /var/vcloud; echo '${other_hosts}' | tr ' ' '\n' > /var/vcloud/other_hosts\";
		tee .vcloud-data | tar jx;
		[ -f ./vcloud-launch ] && { screen -d -m ./vcloud-launch; exit; };
		dirs=(\$(ls -1F | grep '\/$'));
		[ \${#dirs[@]} -eq 1 ] && { cd \${dirs[0]}; screen -d -m ./vcloud-launch; exit; };
		echo Error: vcloud-launch script not found;
		exit 1" &

done
wait
