#!/bin/bash

[ ! -f ${HOME}/.vcloud-reservations ] && { echo 'No reservations found'; exit 1; }
reservations=`cat ${HOME}/.vcloud-reservations`
filters=
for reservation in $reservations; do
	filters="$filters --filter reservation-id=$reservation"
done
instances=`ec2-describe-instances $filters | grep ^INSTANCE | cut -f2`
ec2-terminate-instances $instances && rm ${HOME}/.vcloud-reservations
