#!/bin/bash

#
# Development environment package
#
# This example script enables logging, installs some development packages,
# builds and installs a recent version of the boost libraries, and starts
# building our program
#

dev_packages="curl python-dev python3-dev g++ libbz2-dev zlib1g-dev scons"
python_version=3.1
boost_version=1.45.0
boost_version_uscr=`echo $boost_version | sed 's/\./_/g'`
boost_filename=boost_$boost_version_uscr
suppressed_boost_libraries=date_time,regex,filesystem,graph,graph_parallel,iostreams,math,mpi,program_options,signals,system,test,wave

set -e	# exit immediately on error
# set -x	# echo commands before they expanded and executed
exec > >(tee vcloud-log) 2>&1 # enable logging

echo
echo '*************************************'
echo Dev script launched: `date '+%Y-%m-%d %H:%M:%S'`
echo '*************************************'
echo

export DEBIAN_FRONTEND=noninteractive
date '+%Y-%m-%d %H:%M:%S'
sudo apt-get -qqy update && sudo apt-get -qqy upgrade
sudo apt-get -qqy install $dev_packages

cur_dir=$( pwd )

# build and install boost
build_dir=$( mktemp -d )
cd "$build_dir"
curl -LsS -o ${boost_filename}.tar.bz2 \
	http://sourceforge.net/projects/boost/files/boost/${boost_version}/${boost_filename}.tar.bz2/download
tar jxf ${boost_filename}.tar.bz2 && rm ${boost_filename}.tar.bz2
cd ${boost_filename}
./bootstrap.sh --without-libraries=$suppressed_boost_libraries --with-python-version=$python_version \
	&& sudo ./bjam -j4 -d0 install
cd "$cur_dir"
sudo rm -rf "$build_dir" # needs to be sudo cuz we used sudo during build

# scons		# build our program

echo
echo '**************************************'
echo Dev script complete: `date '+%Y-%m-%d %H:%M:%S'`
echo '**************************************'
echo

