#!/bin/bash

# Deploy package

set -e	# exit immediately on error
# set -x	# echo commands before they expanded and executed
exec > >(tee vcloud-log) 2>&1 # enable logging

echo
echo '*************************************'
echo User script launched: `date '+%Y-%m-%d %H:%M:%S'`
echo '*************************************'
echo

export DEBIAN_FRONTEND=noninteractive
sudo apt-get -qqy update && sudo apt-get -qqy upgrade
sudo apt-get -qqy install curl python python3

# get instance metadata
metadata=http://instance-data/latest/meta-data
dns_name=`curl ${metadata}/public-hostname` #resolves to internal ip within AWS
index=`curl ${metadata}/ami-launch-index`

# can now call our script with any of the following resources
#
#	$dns_name			this host's public DNS name
#	$index				this host's index (hosts are sequentially numbered from 0)
#	/var/vcloud/seeds	address of all *other* hosts (in host:port format, one per line)
#

python3 helloworld.py "#@"

echo
echo '**************************************'
echo User script complete: `date '+%Y-%m-%d %H:%M:%S'`
echo '**************************************'
echo

